export const queryKey = {
    listCard: 'list-card',
    favoriteJobs: 'favorite-jobs',
    listCvofProfile: 'list-cvof-profile',
    me: 'me',
    candidateSocialLinks: 'candidate-social-links',
    listTag: 'list-tag',
    listCategory: 'list-category',
    detailJob: 'detail-job',
    checkEnterprise: 'check-enterprise',
    updateRegisterEnterprises: 'update-register-enterprise',
    enterprise: 'enterprise',
    enterpriseSocialLinks: 'enterprise-social-links',
    categoriesChild: 'searchCategoriesChild',
    categoriesPrimary: 'categories-primary',
    tagList: 'searchTags',
    jobsOfEnterprise: 'jobs-of-enterprise',
    countTotalJobsOfEnterpriseId: 'count-total-jobs-of-enterprise-id',
    listJobs: 'list-jobs',
    filterJob: 'filter-job',
    enterpriseJob: 'enterprise-job',
    ownResumes: 'own-resumes',
};
